# Generated by Django 3.1 on 2021-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=70)),
                ('doctor_name', models.CharField(max_length=70)),
                ('doctor_fees', models.IntegerField(default=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
